### ISSUE TITLE
Angular betweenness

### ISSUE THREAD

**Issue by Robinlovelace** [UrbanAnalyst/dodgr#113]
Is it possible to calculate angular betweenness of edges in a network?

**Comment by mpadge** [comment]
There's a conference paper [here](http://sss9sejong.or.kr/paperpdf/mmd/SSS9_2013_REF057_P.pdf), which shows how this really is a purely spatial syntax phenomenon, requiring initial conversion of a graph into its dual representation. Bill Hillier's fabulously compelling writing notwithstanding, there is still very scarce evidence to suggest great scientific validity to dual graph representations, and the whole thing would be a heap of work for something that would be very unlikely to find general utility. Thoughts?

**Comment by mpadge** [comment]
So maybe "angular betweenness" is not actually the thing we want; rather an option to route paths between two points based on sum of angular change, as in [`sDNA`](https://sdna-open.readthedocs.io/en/latest/analysis-spec.html#distance-metric). That is very straightforward to incorporate. Most functions now have options for distance vs time calculations, so i'd just have to expand that to include angles as an additional option for "distance" metrics. Can do that!

**Comment by mpadge** [comment]
Closing this; can re-open later if desired
