### ISSUE TITLE
General overpass server error

### ISSUE THREAD

**Issue by LinhLTP** [UrbanAnalyst/dodgr#221]
Hi everyone, 

I am using dodgr for my work and encountered this issue:

![image](https://github.com/UrbanAnalyst/dodgr/assets/61450812/59bc46e4-d37e-4b3c-bbd1-281ef40ec0fc)

Could anyone please give me some advice how to deal with this issue? 

Much appreciated!

**Comment by LinhLTP** [comment]
I try to use this code, but the issue can not be solved. 

![image](https://github.com/UrbanAnalyst/dodgr/assets/61450812/affba6e8-262b-4b12-87a5-40b17a3626a6)

Much appreciated if anyone can give me any advice!

**Comment by mpadge** [comment]
That error is unfortunately most likely https://github.com/ropensci/osmdata/issues/170, so not related to this package, or {osmdata} which is used to get the data. The best advice i can give is to ensure all packages are up to date. You should see something like this:
``` r
library(dodgr)
library(osmdata)
#> Data (c) OpenStreetMap contributors, ODbL 1.0. https://www.openstreetmap.org/copyright
packageVersion("dodgr")
#> [1] '0.3.0.8'
packageVersion("osmdata")
#> [1] '0.2.5.5'
```

<sup>Created on 2024-01-17 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>
If the error still persists, you can only really wait and hope that something on the server side resolves itself. The overpass server which delivers the data implements all kinds of clever request throttling based on IP address, current and previous loads, Any queries from you IP address rejected or throttled there will generate that error. I'll close now, but feel free to ask any further questions.

**Comment by LinhLTP** [comment]
Thank you so much for your advice @mpadge
